### ISSUE TITLE
Heading levels 4 & 5: incorrect line break on LibreOffice

### ISSUE THREAD

**Issue by writernotcoder** [wjschne/apaquarto#32]
First: THANK YOU for this amazing extension. 

I've had this same issue using the previous version and also in the new 3.1.0 release, and I'm guessing it's on my end since I'm not seeing others report it, but maybe you can help? I'm outputting to docx and I don't have Word installed, I use Open Office or Libre Office. 

Level 4 and Level 5 headings have appropriate indenting and character formatting (bold/italic respectively) but they both put a line break, and subsequent text is beginning on the next line instead of on the same line as the heading. I just tested it on your template qmd and I'm getting the same behavior. 

Any ideas? Is this something I need to adjust in my local LibreOffice styles? 

TIA!

**Comment by wjschne** [comment]
Glad you like the extension!

The problem is not yours but that there are MS Word features not implemented in LibreOffice. I did not know this was one of them at the time I implemented the solution I ended up choosing. I will think about finding a solution that works for everyone. In the meantime, implemented a workaround in version 3.1.2. It is not documented, but you can get level 4 and 5 headings like so:

```md
[This Is a Level-4 Heading]{.H4} This is a paragraph after a level-4 heading.

[This Is a Level-5 Heading]{.H5} This is a paragraph after a level-4 heading.
```

This solution does not make the headings true headings. They are spans with classes that map onto custom character styles in the apaquarto.docx reference template.

Let me know if this works for you.

**Comment by writernotcoder** [comment]
Wow, thanks for the fast response! I am still seeing the same issue on my end however I may not have 3.1.2 installed correctly yet, so let me circle back again after I've had more time to fiddle with my setup/Quarto etc. Thanks!

**Comment by writernotcoder** [comment]
Welp something weird is happening now, I may have trashed my environment in attempting to upgrade. I am on 3.2.2 and not only is it not yet showing the Heading Levels 4 or 5 correctly on LibreOffice, but now I also cannot get the BetterBibText citations to render into the docx file at all.

**Comment by wjschne** [comment]
Not sure what might be happening. I am happy to meet over zoom to figure it out. Contact me at schneider@temple.edu

**Comment by writernotcoder** [comment]
That's very generous of you! I rolled back to the old version (trying to get this dissertation done!) but I may return to the new one in a few weeks if I have time to devote to this later. If I hit the same issue again I will reach out then, for now I'll just thank you for the attempts to help, I appreciate it!

**Comment by mvuorre** [comment]
I sometimes use LibreOffice and so tried this with v24.2. References work fine but for me the headings produce following paragraphs that are bolded in LibreOffice (Word works fine).

This source:

```markdown
---
title: "My Title"
shorttitle: "Short Title in Running Header"
author:
  - name: Jane Doe
    corresponding: true
    orcid: 0000-0000-0000-0001
    email: janedoe@generic.edu
    affiliations:
      - name: Generic University
        department: Department of Scholarly Studies
        address: 1234 Capital St.
        city: New York
        region: NY
        country: USA
        postal-code: 12084-1234
author-note:
  status-changes: 
    affiliation-change: ~
    deceased: ~
  disclosures:
    study-registration: ~
    data-sharing: ~
    related-report: ~
    conflict-of-interest: ~
    financial-support: ~
    gratitude: ~
    authorship-agreements: ~
abstract: "This document is a template."
keywords: [keyword1, keyword2, keyword3]
bibliography: references.bib
format:
  apaquarto-docx: default
  apaquarto-html: default
  apaquarto-pdf:
    documentmode: man
---

# Level 1

Level 1

Citation [@schneiderCattellHornCarrollTheoryCognitive2018]

## Level 2

Level 2

### Level 3

Level 3

#### Level 4

Level 4

[This Is a Level-4 Heading]{.H4} This is a paragraph after a level-4 heading hack.

[This Is a Level-5 Heading]{.H5} This is a paragraph after a level-5 heading hack.

##### Level 5

Level 5

# Level 1 again

```

Produces the attached file that looks like this (LibreOffice on the left, Word on the right):

<img width="1993" alt="image" src="https://github.com/wjschne/apaquarto/assets/7349270/c4de4d04-ef9e-4b20-8eab-f7380e15a878">

So this is a LibreOffice feature and can't really be fixed within apaquarto since it supports only the .docx format and not its interpretations in other apps?


Output file: [minimal.docx](https://github.com/wjschne/apaquarto/files/14915155/minimal.docx)

**Comment by wjschne** [comment]
@mvuorre, the regular level-4 and level-5 headings do not work in LibreOffice because it does not implement the "Style Separator" like .docx does.  Are the hacks not working as intended?

Can you think of a way to get LibreOffice to recognize the "Style Separator" feature in that Word offers? Is there some other way to get a header and paragraph to appear in the same paragraph?

**Comment by mvuorre** [comment]
Hi, sorry that I was not clear: The hacks do work as intended (left picture), and there afaik is no way to make the headings work without this hack in LibreOffice. So I meant that it is unlikely that the Word output of pandoc/quarto can be made to work 100% in programs other than Microsoft Word :( (and so it is unlikely that this issue will be fixed on the apaquarto side)
